version: "3.8"

services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.49.6
    container_name: artifactory-tlv
    restart: always
    ports:
      - "8081:8081" # Artifactory UI/API
      - "8082:8082" # JFrog Router
    environment:
      # This ensures Artifactory knows its own name for internal redirects
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=8082
    volumes:
      # Fix: Map to the correct internal path /var/opt/jfrog/artifactory
      - /opt/artifactory:/var/opt/jfrog/artifactory
    networks:
      my-network:
        aliases:
          - artifactory-tlv

networks:
  my-network:
    external: true