timestamps{
  node('zip-job-docker') {
    
    def zipJobImage = 'zip_job_image:latest'
    def gitVars
    def artifactoryID = 'artifactory-server'
    def pythonScript = 'zip_job.py'
    def artifactoryRepo = 'generic-local'
    def mailRecipients = 'ofekrubin1996@gmail.com'

    try {
      stage('Checkout') {
        gitVars = checkout scm
        echo "repo cloned ${gitVars.GIT_URL}"
        sh "ls -la"
      }
      stage('Build') {
          docker.image(zipJobImage).inside {
            echo "Successfully running inside the container!"
            sh "python3 ${pythonScript}"
            sh "ls -la"
          }
      }
      stage('Publish') {
        sh "ls -la"
        def server = Artifactory.server('artifactory-server')
        def uploadSpec = """{
          "files": [
            {
              "pattern": "*.zip",
              "target": "${artifactoryRepo}/"
            }
          ]
        }"""
        server.upload(uploadSpec)
        echo "Artifact uploaded successfully to Artifactory!"
        currentBuild.result = 'SUCCESS'
      }
    } 
    
    catch (err) {
        echo "Build failed: ${err}"
        currentBuild.result = 'FAILURE'
    } 
    
    finally {
      stage('Cleanup') {
        deleteDir()
        echo "workspace cleaned!"
      }
      stage ('Send Notification') {
        emailext(
        subject: "Build ${currentBuild.result}: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
        body: "Check console output at: ${env.BUILD_URL}",
        to: mailRecipients
        )
      }
        //def result = currentBuild.result ?: 'SUCCESS' //if result is null, set it to SUCCESS
        //
        //if (result == 'SUCCESS') {
        //  emailext(
        //      subject: "Build Successful",
        //      body: "Your scripted pipeline build succeeded. Good job!",
        //      to: "ofekrubin1996@gmail.com",
        //      recipientProviders: [requestor(), developers(), culprits()]
        //  )
        //} else if (result == 'FAILURE') {
        //  emailext(
        //      subject: "Build Failed",
        //      body: "Your scripted pipeline build failed. Please check the logs.",
        //      to: "ofekrubin1996@gmail.com",
        //      recipientProviders: [requestor(), developers(), culprits()]
        //  )
        //}
      //}
    }
  }
}