timestamps{
  node('zip-job-docker') {
    
    def zipJobImage = 'zip_job_image:latest'
    def gitVars
    def artifactoryID = 'artifactory-server'
    def pythonScript = 'zip_job.py'
    def artifactoryRepo = 'generic-local'
    def teamList = [
    'ofekrubin1996@gmail.com',
    'mayh98@gmail.com'
    ]
    def mailRecipients = teamList.join(', ')

    try {
      stage('Checkout') {
        gitVars = checkout scm
        echo "repo cloned ${gitVars.GIT_URL}"
        sh "ls -la"
      }
      stage('Build') {
          docker.image(zipJobImage).inside {
            echo "Successfully running inside the container!"
            sh "python3 ${pythonScript}"
            sh "ls -la"
          }
      }
      stage('Publish') {
        def server = Artifactory.server('artifactory-server')
        def files = ['a', 'b', 'c', 'd']
        def uploadSpec

        files.each { file ->
          uploadSpec = """{
            "files": [
              {
                "pattern": "${file}_1.2.0.zip",
                "target": "${artifactoryRepo}/"
              }
            ]
          }"""
        server.upload(uploadSpec)
        echo "Artifact ${file}_1.2.0.zip successfully uploaded to Artifactory!"
        }
        
        
        currentBuild.result = 'SUCCESS'
      }
    } 
    
    catch (err) {
        echo "Build failed: ${err}"
        currentBuild.result = 'FAILURE'
    } 
    
    finally {
      stage('Cleanup') {
        deleteDir()
        echo "workspace cleaned!"
      }
      stage ('Send Notification') {
        emailext(
        subject: "Build ${currentBuild.result}: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
        body: "Check console output at: ${env.BUILD_URL}",
        to: mailRecipients
        )
      }
    }
  }
}